package controller;

import javafx.collections.*;import javafx.collections.transformation.FilteredList;import javafx.concurrent.Task;import javafx.event.ActionEvent;import javafx.fxml.*;import javafx.scene.Parent;import javafx.scene.control.*;import javafx.scene.control.cell.PropertyValueFactory;import javafx.scene.input.MouseButton;import service.*;import sv.asociacion.backend.entity.*;import java.text.Normalizer;import java.util.*;

public class ViviendaController {
 @FXML private TableView<Vivienda> tablaViviendas;@FXML private TableColumn<Vivienda,String> colCodigo,colSector,colDireccion,colRepresentante,colEstado;@FXML private TableColumn<Vivienda,Integer> colAdultos,colMenores;@FXML private Label lblTotal,lblHabitantes,lblEstadoModulo;@FXML private TextField campoBusqueda;@FXML private Button btnVerDetalle,btnEditar,btnDesactivar;
 private final ObservableList<Vivienda> viviendas=FXCollections.observableArrayList();private final List<Miembro> miembros=new ArrayList<>();private FilteredList<Vivienda> filtered;private final ViviendaApiClient api=new ViviendaApiClient();
 @FXML private void initialize(){tablaViviendas.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);colCodigo.setCellValueFactory(new PropertyValueFactory<>("codigo"));colSector.setCellValueFactory(new PropertyValueFactory<>("sector"));colDireccion.setCellValueFactory(new PropertyValueFactory<>("direccion"));colRepresentante.setCellValueFactory(new PropertyValueFactory<>("representante"));colAdultos.setCellValueFactory(new PropertyValueFactory<>("adultos"));colMenores.setCellValueFactory(new PropertyValueFactory<>("menores"));colEstado.setCellValueFactory(new PropertyValueFactory<>("estado"));filtered=new FilteredList<>(viviendas,v->true);tablaViviendas.setItems(filtered);campoBusqueda.textProperty().addListener((o,a,b)->filter(b));btnVerDetalle.disableProperty().bind(tablaViviendas.getSelectionModel().selectedItemProperty().isNull());btnEditar.disableProperty().bind(tablaViviendas.getSelectionModel().selectedItemProperty().isNull());btnDesactivar.disableProperty().bind(tablaViviendas.getSelectionModel().selectedItemProperty().isNull());tablaViviendas.setRowFactory(t->{TableRow<Vivienda> r=new TableRow<>();r.setOnMouseClicked(e->{if(!r.isEmpty()&&e.getButton()==MouseButton.PRIMARY&&e.getClickCount()==2)showDetail(r.getItem());});return r;});load();}
 private void load(){run("Conectando al servidor...",()->{var houses=api.findAll();var members=new MiembroApiClient().findAll();return new Load(houses,members);},value->{viviendas.setAll(value.houses());miembros.clear();miembros.addAll(value.members());lblEstadoModulo.setText("Conectado al servidor");updateTotals();});}
 @FXML private void nueva(){openForm(null);}@FXML private void editar(){openForm(tablaViviendas.getSelectionModel().getSelectedItem());}
 @FXML private void verDetalle(){Vivienda selected=tablaViviendas.getSelectionModel().getSelectedItem();if(selected!=null)showDetail(selected);}
 private void showDetail(Vivienda house){run("Consultando vivienda...",()->api.find(house.getIdVivienda()),detail->{try{FXMLLoader loader=new FXMLLoader(getClass().getResource("/fxml/views/detalle-vivienda.fxml"));Parent content=loader.load();DetalleViviendaController controller=loader.getController();controller.setDetail(detail);Dialog<Void> dialog=new Dialog<>();dialog.initOwner(tablaViviendas.getScene().getWindow());dialog.setTitle("Detalle de vivienda "+house.getCodigo());dialog.getDialogPane().setContent(content);dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);dialog.getDialogPane().getStyleClass().add("member-dialog");var css=getClass().getResource("/styles/member-dialog.css");if(css!=null)dialog.getDialogPane().getStylesheets().add(css.toExternalForm());lblEstadoModulo.setText("Conectado al servidor");dialog.showAndWait();}catch(Exception e){error("No fue posible mostrar el detalle: "+e.getMessage());}});}
 private void openForm(Vivienda house){if(miembros.isEmpty()){error("No hay miembros disponibles para asignar como representantes.");return;}try{FXMLLoader loader=new FXMLLoader(getClass().getResource("/fxml/views/vivienda-form.fxml"));Parent content=loader.load();ViviendaFormController form=loader.getController();form.setMembers(miembros);if(house!=null){var detail=api.find(house.getIdVivienda());form.setHouse(detail.vivienda(),detail.residentes());}ButtonType save=new ButtonType(house==null?"Registrar vivienda":"Guardar cambios",ButtonBar.ButtonData.OK_DONE);Dialog<Void> dialog=new Dialog<>();dialog.initOwner(tablaViviendas.getScene().getWindow());dialog.setTitle(house==null?"Nueva vivienda":"Editar vivienda");dialog.getDialogPane().setContent(content);dialog.getDialogPane().getButtonTypes().addAll(save,ButtonType.CANCEL);dialog.getDialogPane().getStyleClass().add("member-dialog");var css=getClass().getResource("/styles/member-dialog.css");if(css!=null)dialog.getDialogPane().getStylesheets().add(css.toExternalForm());Button button=(Button)dialog.getDialogPane().lookupButton(save);button.addEventFilter(ActionEvent.ACTION,e->{e.consume();var request=form.request();if(request==null)return;button.setDisable(true);run("Guardando vivienda...",()->house==null?api.create(request):api.update(house.getIdVivienda(),request),saved->{if(house==null)viviendas.add(saved);else viviendas.set(viviendas.indexOf(house),saved);updateTotals();dialog.close();});});dialog.showAndWait();}catch(Exception e){error(e.getMessage());}}
 @FXML private void desactivar(){Vivienda v=tablaViviendas.getSelectionModel().getSelectedItem();if(v==null)return;Alert a=new Alert(Alert.AlertType.CONFIRMATION,"La vivienda conservará todo su historial.",ButtonType.YES,ButtonType.NO);a.setHeaderText("¿Desactivar "+v.getCodigo()+"?");if(a.showAndWait().orElse(ButtonType.NO)!=ButtonType.YES)return;run("Desactivando...",()->{api.deactivate(v.getIdVivienda());return v;},done->{v.setEstado("INACTIVA");tablaViviendas.refresh();updateTotals();});}
 private <T> void run(String status,Work<T> work,java.util.function.Consumer<T> success){lblEstadoModulo.setText(status);Task<T> task=new Task<>(){protected T call()throws Exception{return work.run();}};task.setOnSucceeded(e->success.accept(task.getValue()));task.setOnFailed(e->{lblEstadoModulo.setText("Error de conexión");error(task.getException()==null?"Error desconocido":task.getException().getMessage());});Thread thread=new Thread(task,"viviendas-api");thread.setDaemon(true);thread.start();}
 private void filter(String text){String q=normalize(text);filtered.setPredicate(v->q.isBlank()||contains(v.getCodigo(),q)||contains(v.getSector(),q)||contains(v.getDireccion(),q)||contains(v.getRepresentante(),q));updateTotals();}
 private void updateTotals(){lblTotal.setText(filtered.size()+" viviendas");lblHabitantes.setText(filtered.stream().mapToInt(Vivienda::getTotalResidentes).sum()+" residentes registrados");}
 private boolean contains(String v,String q){return v!=null&&normalize(v).contains(q);}private String normalize(String v){return v==null?"":Normalizer.normalize(v,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase().trim();}private void error(String m){new Alert(Alert.AlertType.ERROR,m,ButtonType.OK).showAndWait();}
 private record Load(List<Vivienda> houses,List<Miembro> members){}@FunctionalInterface private interface Work<T>{T run()throws Exception;}
}
